steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ai-business-backend:v1', '.']
    
  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ai-business-backend:v1']

images:
  - 'gcr.io/$PROJECT_ID/ai-business-backend:v1'

# Specify Cloud Logging for build logs
options:
  logging: CLOUD_LOGGING_ONLY
